INFO 2023-12-02 12:42:52,005 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:43:52,529 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-02 12:43:53,257 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:46:01,176 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-02 12:46:01,701 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:48:30,508 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/__init__.py changed, reloading.
INFO 2023-12-02 12:48:30,903 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:49:15,871 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:51:09,940 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-02 12:51:14,001 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-02 12:51:14,048 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-12-02 12:51:14,087 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-02 12:51:14,088 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-02 12:51:14,090 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-03 12:43:49,136 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-03 12:44:13,290 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-03 12:44:13,307 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-12-03 12:44:13,385 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-03 12:44:13,387 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-03 12:44:13,387 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
WARNING 2023-12-03 12:44:13,404 log 224 Not Found: /favicon.ico
WARNING 2023-12-03 12:44:13,405 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 1998
INFO 2023-12-04 10:27:42,741 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 10:28:40,416 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-12-04 10:28:42,853 exception 99 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2023-12-04 10:28:42,913 log 224 Bad Request: /
WARNING 2023-12-04 10:28:42,913 basehttp 161 "GET / HTTP/1.1" 400 70259
ERROR 2023-12-04 10:28:43,265 exception 99 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2023-12-04 10:28:43,309 log 224 Bad Request: /favicon.ico
WARNING 2023-12-04 10:28:43,309 basehttp 161 "GET /favicon.ico HTTP/1.1" 400 70310
INFO 2023-12-04 10:28:51,209 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-04 10:28:51,229 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-12-04 10:28:51,319 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-04 10:28:51,321 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-04 10:28:51,329 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
WARNING 2023-12-04 10:28:51,349 log 224 Not Found: /favicon.ico
WARNING 2023-12-04 10:28:51,350 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 1998
INFO 2023-12-04 10:31:41,316 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 10:31:41,856 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 10:33:36,919 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-04 10:33:36,930 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2023-12-04 10:33:37,029 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2023-12-04 10:33:37,040 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2023-12-04 10:33:37,050 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
WARNING 2023-12-04 10:33:37,066 log 224 Not Found: /favicon.ico
WARNING 2023-12-04 10:33:37,072 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2002
INFO 2023-12-04 10:35:06,555 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 10:38:03,066 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-04 10:40:48,238 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 10:40:49,919 basehttp 161 code 400, message Bad request version ('\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01Äºº\x00\x00\x00+\x00\x07\x06ºº\x03\x04\x03\x03ÿ\x01\x00\x01\x00\x003\x00+\x00)')
ERROR 2023-12-04 10:40:49,919 basehttp 142 You're accessing the development server over HTTPS, but it only supports HTTP.

INFO 2023-12-04 10:40:49,920 basehttp 161 code 400, message Bad request version ('\x03Ò\x96ldÊs\x19Lv')
ERROR 2023-12-04 10:40:49,921 basehttp 142 You're accessing the development server over HTTPS, but it only supports HTTP.

INFO 2023-12-04 10:40:49,942 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-12-04 10:40:49,959 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2023-12-04 10:40:50,043 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2023-12-04 10:40:50,044 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
WARNING 2023-12-04 10:40:50,072 log 224 Not Found: /favicon.ico
WARNING 2023-12-04 10:40:50,074 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2003
INFO 2023-12-04 10:40:50,074 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2023-12-04 10:46:06,876 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 10:46:07,347 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 10:54:05,680 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 14:04:33,352 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 14:06:46,628 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 14:26:26,378 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-12-04 14:27:40,780 exception 99 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-12-04 14:27:40,813 log 224 Bad Request: /users/authorizations/
WARNING 2023-12-04 14:27:40,813 basehttp 161 "GET /users/authorizations/ HTTP/1.1" 400 70885
WARNING 2023-12-04 14:28:20,876 log 224 Not Found: /users/authorizations/
WARNING 2023-12-04 14:28:20,876 basehttp 161 "GET /users/authorizations/ HTTP/1.1" 404 2192
WARNING 2023-12-04 14:28:30,091 log 224 Not Found: /users/
WARNING 2023-12-04 14:28:30,092 basehttp 161 "GET /users/ HTTP/1.1" 404 2147
WARNING 2023-12-04 14:29:06,975 log 224 Not Found: /users/authorizations/
WARNING 2023-12-04 14:29:06,975 basehttp 161 "POST /users/authorizations/ HTTP/1.1" 404 2193
WARNING 2023-12-04 14:29:23,029 log 224 Not Found: /users/
WARNING 2023-12-04 14:29:23,031 basehttp 161 "POST /users/ HTTP/1.1" 404 2148
ERROR 2023-12-04 14:29:28,914 log 224 Internal Server Error: /users/login
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.renran.com:8000/users/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2023-12-04 14:29:28,915 basehttp 161 "POST /users/login HTTP/1.1" 500 71756
WARNING 2023-12-04 14:33:45,018 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:33:45,019 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
WARNING 2023-12-04 14:33:56,983 log 224 Not Found: /users/authorizations/
WARNING 2023-12-04 14:33:56,983 basehttp 161 "POST /users/authorizations/ HTTP/1.1" 404 2193
WARNING 2023-12-04 14:34:02,187 log 224 Not Found: /users/
WARNING 2023-12-04 14:34:02,188 basehttp 161 "POST /users/ HTTP/1.1" 404 2148
WARNING 2023-12-04 14:34:07,899 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:34:07,900 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
WARNING 2023-12-04 14:34:19,573 log 224 Method Not Allowed: /users/login/
WARNING 2023-12-04 14:34:19,574 basehttp 161 "GET /users/login/ HTTP/1.1" 405 40
WARNING 2023-12-04 14:34:25,002 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:34:25,002 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
INFO 2023-12-04 14:35:41,528 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 14:35:41,999 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-04 14:35:45,008 log 224 Not Found: /users/login
WARNING 2023-12-04 14:35:45,009 basehttp 161 "POST /users/login HTTP/1.1" 404 2163
WARNING 2023-12-04 14:36:23,052 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:36:23,053 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
WARNING 2023-12-04 14:36:25,116 log 224 Not Found: /users/login
WARNING 2023-12-04 14:36:25,116 basehttp 161 "POST /users/login HTTP/1.1" 404 2163
WARNING 2023-12-04 14:36:27,997 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:36:27,998 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
INFO 2023-12-04 14:39:29,196 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 14:39:31,044 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-12-04 14:39:39,435 exception 99 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2023-12-04 14:39:39,488 log 224 Bad Request: /
WARNING 2023-12-04 14:39:39,490 basehttp 161 "GET / HTTP/1.1" 400 71179
ERROR 2023-12-04 14:39:39,664 exception 99 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2023-12-04 14:39:39,704 log 224 Bad Request: /favicon.ico
WARNING 2023-12-04 14:39:39,705 basehttp 161 "GET /favicon.ico HTTP/1.1" 400 71230
ERROR 2023-12-04 14:39:54,010 exception 99 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-12-04 14:39:54,050 log 224 Bad Request: /
WARNING 2023-12-04 14:39:54,051 basehttp 161 "GET / HTTP/1.1" 400 72283
ERROR 2023-12-04 14:39:54,109 exception 99 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-12-04 14:39:54,134 log 224 Bad Request: /favicon.ico
WARNING 2023-12-04 14:39:54,135 basehttp 161 "GET /favicon.ico HTTP/1.1" 400 72208
WARNING 2023-12-04 14:40:15,792 log 224 Not Found: /
WARNING 2023-12-04 14:40:15,793 basehttp 161 "GET / HTTP/1.1" 404 2058
WARNING 2023-12-04 14:40:15,829 log 224 Not Found: /favicon.ico
WARNING 2023-12-04 14:40:15,829 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2109
WARNING 2023-12-04 14:40:22,514 log 224 Not Found: /users
WARNING 2023-12-04 14:40:22,514 basehttp 161 "GET /users HTTP/1.1" 404 2091
WARNING 2023-12-04 14:40:25,877 log 224 Not Found: /users/
WARNING 2023-12-04 14:40:25,877 basehttp 161 "GET /users/ HTTP/1.1" 404 2147
INFO 2023-12-04 14:41:02,485 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 14:41:03,560 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-04 14:41:09,657 log 224 Not Found: /users
WARNING 2023-12-04 14:41:09,659 basehttp 161 "GET /users HTTP/1.1" 404 2091
INFO 2023-12-04 14:41:16,174 basehttp 161 "GET /users/login HTTP/1.1" 301 0
ERROR 2023-12-04 14:41:16,216 log 224 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-04 14:41:16,217 basehttp 161 "GET /users/login/ HTTP/1.1" 500 82748
ERROR 2023-12-04 14:42:45,317 log 224 Internal Server Error: /users/login
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.renran.com:8000/users/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2023-12-04 14:42:45,318 basehttp 161 "POST /users/login HTTP/1.1" 500 71853
INFO 2023-12-04 14:43:04,898 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 14:43:05,453 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-04 14:43:13,569 log 224 Not Found: /users/login
WARNING 2023-12-04 14:43:13,569 basehttp 161 "POST /users/login HTTP/1.1" 404 2163
WARNING 2023-12-04 14:43:17,574 log 224 Bad Request: /users/login/
WARNING 2023-12-04 14:43:17,574 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
INFO 2023-12-04 14:47:02,048 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 14:47:02,549 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-04 15:13:43,442 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-04 15:13:45,241 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 02:18:41,495 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 02:18:56,676 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 02:19:26,902 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 03:07:46,158 basehttp 161 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2023-12-05 03:07:46,235 log 224 Bad Request: /users/login/
WARNING 2023-12-05 03:07:46,235 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2023-12-05 03:17:16,548 log 224 Bad Request: /users/login/
WARNING 2023-12-05 03:17:16,549 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2023-12-05 03:20:52,676 log 224 Bad Request: /users/login/
WARNING 2023-12-05 03:20:52,678 basehttp 161 "POST /users/login/ HTTP/1.1" 400 79
WARNING 2023-12-05 03:21:16,692 log 224 Bad Request: /users/login/
WARNING 2023-12-05 03:21:16,692 basehttp 161 "POST /users/login/?username=root&passwoed=123 HTTP/1.1" 400 79
INFO 2023-12-05 03:21:41,010 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-05 03:21:52,871 log 224 Bad Request: /users/login/
WARNING 2023-12-05 03:21:52,872 basehttp 161 "POST /users/login/?username=root&passwoed=123 HTTP/1.1" 400 79
INFO 2023-12-05 08:41:19,947 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-12-05 08:41:41,937 exception 99 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-12-05 08:41:41,984 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:41:41,985 basehttp 161 "POST /users/login/?username=root&password=123 HTTP/1.1" 400 71920
INFO 2023-12-05 08:42:47,597 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-05 08:42:48,174 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-05 08:42:49,642 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:42:49,642 basehttp 161 "POST /users/login/?username=root&password=123 HTTP/1.1" 400 79
WARNING 2023-12-05 08:44:05,775 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:44:05,776 basehttp 161 "POST /users/login/?username=root&password=root123456 HTTP/1.1" 400 79
ERROR 2023-12-05 08:47:05,954 log 224 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework_jwt/views.py", line 60, in post
    response_data = jwt_response_payload_handler(token, user, request)
  File "/home/xzx/Desktop/renran/renranapi/renranapi/apps/users/utils.py", line 15, in jwt_response_payload_handler
    'avatar': user.avatar.url,
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/db/models/fields/files.py", line 62, in url
    self._require_file()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/db/models/fields/files.py", line 39, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'avatar' attribute has no file associated with it.
ERROR 2023-12-05 08:47:05,957 basehttp 161 "POST /users/login/ HTTP/1.1" 500 107482
INFO 2023-12-05 08:53:41,924 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-12-05 08:53:50,254 log 224 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework_jwt/views.py", line 60, in post
    response_data = jwt_response_payload_handler(token, user, request)
  File "/home/xzx/Desktop/renran/renranapi/renranapi/apps/users/utils.py", line 16, in jwt_response_payload_handler
    'nickname': user.nickname,
AttributeError: 'User' object has no attribute 'nickname'
ERROR 2023-12-05 08:53:50,256 basehttp 161 "POST /users/login/ HTTP/1.1" 500 100113
INFO 2023-12-05 08:55:16,460 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 08:55:19,873 basehttp 161 "POST /users/login/ HTTP/1.1" 200 210
INFO 2023-12-05 08:56:19,683 basehttp 161 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2023-12-05 08:56:19,688 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:56:19,688 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2023-12-05 08:56:26,088 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:56:26,089 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2023-12-05 08:56:32,416 log 224 Bad Request: /users/login/
WARNING 2023-12-05 08:56:32,417 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2023-12-05 09:13:25,966 log 224 Bad Request: /users/login/
WARNING 2023-12-05 09:13:25,967 basehttp 161 "POST /users/login/ HTTP/1.1" 400 89
INFO 2023-12-05 09:15:28,758 basehttp 161 "POST /users/login/ HTTP/1.1" 200 210
INFO 2023-12-05 09:22:29,288 basehttp 161 "POST /users/login/ HTTP/1.1" 200 210
WARNING 2023-12-05 09:23:32,520 log 224 Bad Request: /users/login/
WARNING 2023-12-05 09:23:32,520 basehttp 161 "POST /users/login/ HTTP/1.1" 400 68
INFO 2023-12-05 09:26:07,111 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/utils.py changed, reloading.
INFO 2023-12-05 09:26:07,937 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-05 09:27:28,466 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
WARNING 2023-12-05 09:39:58,510 log 224 Bad Request: /users/captcha/
WARNING 2023-12-05 09:39:58,515 basehttp 161 "GET /users/captcha/?ticket=t03EMD-ATQmUlEoRWlZ9Y0vJox3KjxyUPkOw7WM4AHHcWCxilJoIFKNoeNGQMsqrSppKdz_nCL8YWkGFvvRskvJsFVMXo6NxlvTqxkMDS-VKMGbwEPVaND2__GYDZXJJcVB&randstr=%40FFO HTTP/1.1" 400 48
WARNING 2023-12-05 09:40:15,450 log 224 Bad Request: /users/captcha/
WARNING 2023-12-05 09:40:15,453 basehttp 161 "GET /users/captcha/?ticket=t03FWQfLTnnr3fYTDIwHjNHFKJ10YJxbVMqnsRGIHTGlXS9_G1ReFsgouyFYesY7QeNnTOCHuV2sX_b8z8KmLhZ3oKVpRIG0nObtVRxtXhx1POQffwsnp3EaHnIsHj3UIbA&randstr=%40iEc HTTP/1.1" 400 48
WARNING 2023-12-05 09:40:31,176 log 224 Bad Request: /users/captcha/
WARNING 2023-12-05 09:40:31,177 basehttp 161 "GET /users/captcha/?ticket=t03Lt10PLwoYVqQdaw3vz4WOXRI7GgfmPRV_R7XQtWPVQAXaQJbb-GBPdHU93fKY0qnxDTCBjCsJHdsZmKHLCs2Zsz1hMo33jDrDsirPa-Wa_DnrVZFJHm69Msa_asVy6at&randstr=%40xuC HTTP/1.1" 400 48
WARNING 2023-12-05 09:45:12,119 log 224 Bad Request: /users/captcha/
WARNING 2023-12-05 09:45:12,121 basehttp 161 "GET /users/captcha/?ticket=t0333ycH7nXFwVX-TQiB7vR4LSWJHCJESAY38Q-ENymNAQsMgLk7njYrRhNeEPTdgJR2Isr9vuyw7Sjz3V48A7m6gSfh_-9JPKeAkhnXWuHm29lGFP19xAItU0zpIIvvor4&randstr=%40QQr HTTP/1.1" 400 48
INFO 2023-12-06 03:14:52,062 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-12-06 03:24:52,683 log 224 Bad Request: /users/captcha/
WARNING 2023-12-06 03:24:52,687 basehttp 161 "GET /users/captcha/?ticket=t03NgB36kaeDC3Zgw_neY7z68M5OiMXH6CcPRSMn86Xjl04mQsee4zq9brmb_VdCOwYLMnQbFnOYsR5yLBOxOkUFr_kN-ldsln1YChB_6gyBiMjzsUQgktsbgHuwlflq6vN&randstr=%40j52 HTTP/1.1" 400 48
WARNING 2023-12-06 03:26:45,017 log 224 Bad Request: /users/captcha/
WARNING 2023-12-06 03:26:45,017 basehttp 161 "GET /users/captcha/?ticket=t03wQwND-WWnFOqb_YDuqo2FxJDopJr7eKwW0IyIYCtklDHXCSppz8crqBm6RZmXEpLfRRbEneTRortGR2ZnV6bKK6mc2eTptxzN_DgihwuDdTaYK4F05OccK6dD7Hf2jKl&randstr=%400lz HTTP/1.1" 400 48
INFO 2023-12-06 03:31:12,386 basehttp 161 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2023-12-06 03:31:12,520 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 03:31:22,325 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 03:31:32,267 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 03:53:52,443 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
WARNING 2023-12-06 04:02:25,113 log 224 Not Found: /
WARNING 2023-12-06 04:02:25,115 basehttp 161 "GET / HTTP/1.1" 404 2053
WARNING 2023-12-06 04:02:27,938 log 224 Not Found: /admin
WARNING 2023-12-06 04:02:27,938 basehttp 161 "GET /admin HTTP/1.1" 404 2086
WARNING 2023-12-06 04:02:27,996 log 224 Not Found: /favicon.ico
WARNING 2023-12-06 04:02:27,998 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2104
INFO 2023-12-06 04:02:35,737 basehttp 161 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-12-06 04:02:35,810 basehttp 161 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2214
INFO 2023-12-06 04:02:35,869 basehttp 161 "GET /static/admin/css/base.css HTTP/1.1" 200 19513
INFO 2023-12-06 04:02:35,870 basehttp 161 "GET /static/admin/css/login.css HTTP/1.1" 200 939
INFO 2023-12-06 04:02:35,873 basehttp 161 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
INFO 2023-12-06 04:02:35,875 basehttp 161 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
INFO 2023-12-06 04:02:35,880 basehttp 161 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
INFO 2023-12-06 04:02:35,930 basehttp 161 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-12-06 04:02:36,021 basehttp 161 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-06 04:02:36,022 basehttp 161 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-06 04:02:40,232 basehttp 161 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-12-06 04:02:40,269 basehttp 161 "GET /admin/ HTTP/1.1" 200 2921
INFO 2023-12-06 04:02:40,325 basehttp 161 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
INFO 2023-12-06 04:02:40,377 basehttp 161 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-12-06 04:02:40,378 basehttp 161 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2023-12-06 04:02:40,415 basehttp 161 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-12-06 04:03:25,539 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/settings/dev.py changed, reloading.
INFO 2023-12-06 12:03:51,060 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 12:04:07,852 basehttp 161 "GET /admin/ HTTP/1.1" 200 2877
WARNING 2023-12-06 12:04:15,224 log 224 Not Found: /
WARNING 2023-12-06 12:04:15,225 basehttp 161 "GET / HTTP/1.1" 404 2053
INFO 2023-12-06 12:04:19,558 basehttp 161 "GET /admin/ HTTP/1.1" 200 2877
INFO 2023-12-06 12:04:26,550 basehttp 161 "GET /admin/auth/group/ HTTP/1.1" 200 4416
INFO 2023-12-06 12:04:26,562 basehttp 161 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
INFO 2023-12-06 12:04:26,576 basehttp 161 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2023-12-06 12:04:26,580 basehttp 161 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
INFO 2023-12-06 12:04:26,585 basehttp 161 "GET /static/admin/js/actions.js HTTP/1.1" 200 6540
INFO 2023-12-06 12:04:26,588 basehttp 161 "GET /admin/jsi18n/ HTTP/1.1" 200 8398
INFO 2023-12-06 12:04:26,594 basehttp 161 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
INFO 2023-12-06 12:04:26,596 basehttp 161 "GET /static/admin/js/core.js HTTP/1.1" 200 5698
INFO 2023-12-06 12:04:26,596 basehttp 161 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
INFO 2023-12-06 12:04:26,597 basehttp 161 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2023-12-06 12:04:26,602 basehttp 161 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-12-06 12:04:26,604 basehttp 161 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2023-12-06 12:04:26,660 basehttp 161 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2023-12-06 12:04:35,785 log 224 Not Found: /admin/auth
WARNING 2023-12-06 12:04:35,786 basehttp 161 "GET /admin/auth HTTP/1.1" 404 4032
INFO 2023-12-06 12:05:05,853 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 12:05:15,427 basehttp 161 "GET /admin HTTP/1.1" 301 0
INFO 2023-12-06 12:05:15,485 basehttp 161 "GET /admin/ HTTP/1.1" 200 2877
INFO 2023-12-06 12:07:51,743 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 16:12:52,925 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 16:43:07,580 basehttp 161 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2023-12-06 16:43:07,720 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 17:01:32,726 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/views.py changed, reloading.
INFO 2023-12-06 17:01:33,727 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 17:02:33,188 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/views.py changed, reloading.
INFO 2023-12-06 17:02:33,681 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 17:14:20,543 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/views.py changed, reloading.
INFO 2023-12-06 17:14:21,517 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 17:17:29,023 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 17:21:24,123 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
WARNING 2023-12-06 17:27:36,450 log 224 Bad Request: /users/captcha/
WARNING 2023-12-06 17:27:36,452 basehttp 161 "GET /users/captcha/?ticket=t03LcuMuZKpKiWkxtqcxsydNh4XGjYI6CLh5Nq9qvkStzfQcPbY0sPLplqewrbZ7TMdIpngQ6UzC1VZcIScr4usF8vbiUzXaiPMtXMDrWPTkrFBe84e6aAcQC6Rdns6qjP9&randstr=%40PfV HTTP/1.1" 400 48
INFO 2023-12-06 17:27:53,063 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 17:28:06,037 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
INFO 2023-12-06 17:29:31,806 basehttp 161 "POST /users/login/ HTTP/1.1" 200 222
WARNING 2023-12-06 17:30:36,019 log 224 Not Found: /
WARNING 2023-12-06 17:30:36,023 basehttp 161 "GET / HTTP/1.1" 404 2058
WARNING 2023-12-06 17:30:36,100 log 224 Not Found: /favicon.ico
WARNING 2023-12-06 17:30:36,102 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2109
ERROR 2023-12-06 17:30:44,241 log 224 Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-06 17:30:44,243 basehttp 161 "GET /users/ HTTP/1.1" 500 83088
INFO 2023-12-06 17:30:51,541 basehttp 161 "GET /users HTTP/1.1" 301 0
ERROR 2023-12-06 17:30:51,572 log 224 Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-06 17:30:51,573 basehttp 161 "GET /users/ HTTP/1.1" 500 83088
INFO 2023-12-06 17:31:19,523 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/urls.py changed, reloading.
INFO 2023-12-06 17:31:20,234 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 17:31:22,698 basehttp 161 "GET /users/add HTTP/1.1" 301 0
ERROR 2023-12-06 17:31:22,739 log 224 Internal Server Error: /users/add/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-06 17:31:22,740 basehttp 161 "GET /users/add/ HTTP/1.1" 500 83132
WARNING 2023-12-06 17:31:31,462 log 224 Not Found: /users/
WARNING 2023-12-06 17:31:31,462 basehttp 161 "GET /users/ HTTP/1.1" 404 2465
INFO 2023-12-06 17:31:39,186 basehttp 161 "GET /users/captcha HTTP/1.1" 301 0
ERROR 2023-12-06 17:31:39,497 log 224 Internal Server Error: /users/captcha/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-06 17:31:39,498 basehttp 161 "GET /users/captcha/ HTTP/1.1" 500 83077
WARNING 2023-12-06 17:31:45,758 log 224 Not Found: /users/
WARNING 2023-12-06 17:31:45,759 basehttp 161 "GET /users/ HTTP/1.1" 404 2465
ERROR 2023-12-06 17:31:52,097 log 224 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/rest_framework/renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "/home/xzx/anaconda3/envs/renran/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2023-12-06 17:31:52,098 basehttp 161 "GET /users/login/ HTTP/1.1" 500 83184
INFO 2023-12-06 17:48:50,586 autoreload 250 /home/xzx/Desktop/renran/renranapi/renranapi/apps/users/urls.py changed, reloading.
INFO 2023-12-06 17:48:51,453 autoreload 636 Watching for file changes with StatReloader
INFO 2023-12-06 17:49:29,831 basehttp 161 "OPTIONS /users/ HTTP/1.1" 200 0
WARNING 2023-12-06 17:49:29,848 log 224 Bad Request: /users/
WARNING 2023-12-06 17:49:29,848 basehttp 161 "POST /users/ HTTP/1.1" 400 65
WARNING 2023-12-06 17:49:48,384 log 224 Bad Request: /users/
WARNING 2023-12-06 17:49:48,384 basehttp 161 "POST /users/ HTTP/1.1" 400 87
WARNING 2023-12-06 17:50:08,943 log 224 Bad Request: /users/
WARNING 2023-12-06 17:50:08,943 basehttp 161 "POST /users/ HTTP/1.1" 400 87
WARNING 2023-12-06 18:03:18,036 log 224 Bad Request: /users/
WARNING 2023-12-06 18:03:18,037 basehttp 161 "POST /users/ HTTP/1.1" 400 128
WARNING 2023-12-06 18:05:06,019 log 224 Bad Request: /users/captcha/
WARNING 2023-12-06 18:05:06,019 basehttp 161 "GET /users/captcha/?ticket=t03TVzlasNq3YFDFXbcp3AuXTvBSJg87aDS3cjCiU8DLfhkH326YSpyxJpxNkXixJHyTDERd6s7Idhe1mOzPiWm2UF6_FoZLDrjWbxDqRopSoHN0n3Dzl4HBiUe2gbzFwhT&randstr=%40Zr4 HTTP/1.1" 400 48
